source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'JXPhotoBrowser_Example' do
    pod 'Kingfisher'
    pod 'JXPhotoBrowser', :path => '../'
    pod 'libwebp', '1.0.0'
    pod 'JXPhotoBrowser/KingfisherWebP', :path => '../'

end
