platform :ios, '9.0'

target 'PhotoBrowser' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Kingfisher', '4.10.0'
  ## 普通图片
# pod 'JXPhotoBrowser', :path => '..'

  ## WebP格式的图片
  pod 'libwebp', '1.0.0'
  pod 'JXPhotoBrowser/KingfisherWebP', :path => '..'
end
