platform :ios, '13.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'SDWebImage'
  pod 'Kingfisher'
  pod 'LookinServer', :configurations => ['Debug']

end
